added function for get request
Jana-Mikhierieva/js-winners-team pull request #1
Opened 2024-09-06 18:54 UTC by Mariia-Petlovana-91

2024-09-06 20:56 UTC, Jana-Mikhierieva requested changes

2024-09-06 20:56 UTC, Jana-Mikhierieva commented on src/js/api.js
> +axios.defaults.baseURL = 'https://portfolio-js.b.goit.study/api/reviews';
пропоную убрати слово reviews із axios.defaults.baseURL та поставити ресурс при оголошенні response (рядок 8), для уникнення конфлікту при формуванні запитів на інші ресурси

2024-09-06 20:56 UTC, Jana-Mikhierieva commented on src/js/reviews.js
> +const api = await getReview();
пропоную переменувати змінну, бо тут ми очікуємо данні. Наприклад 'reviews'

2024-09-06 20:56 UTC, Jana-Mikhierieva commented on src/js/api.js
> +	    return response.data;
я не бачу в описі відповіді властивості data) ти вже тестила цей код? мені здається, що воно так не буде працювати) як на мене, то повертати треба просто response))

2024-09-06 20:56 UTC, Jana-Mikhierieva commented on src/js/api.js
> +			message: "Sorry, no Reviews found.",
вважаю, що повідомлення в цьому блоці має бути іншого змісту) по типу "Упс...Щось пішло не так"

2024-09-07 11:24 UTC, Mariia-Petlovana-91 commented on src/js/api.js
> +	    return response.data;
ми ж працюємо через аxios він повертає data

2024-09-07 11:24 UTC, Mariia-Petlovana-91 commented on src/js/reviews.js
> +const api = await getReview();
перероблено

2024-09-07 11:25 UTC, Mariia-Petlovana-91 commented on src/js/api.js
> +			message: "Sorry, no Reviews found.",
ок.

2024-09-07 11:25 UTC, Mariia-Petlovana-91 commented on src/js/api.js
> +axios.defaults.baseURL = 'https://portfolio-js.b.goit.study/api/reviews';
добре

2024-09-07 11:39 UTC, Mariia-Petlovana-91 commented
Внесла зміни

2024-09-07 12:42 UTC, Jana-Mikhierieva approved these changes

2024-09-07 12:42 UTC, merged